### ISSUE TITLE
Client

### ISSUE THREAD

**Issue by hampton1122** [patthiel/docker-kdx-server#1]
Have you done a client version of the KDX software?

**Comment by patthiel** [comment]
I have not looked into this, but it should be possible! I may be able to get something up and running over the next few weeks.

**Comment by patthiel** [comment]
I'm looking into this right now @hampton1122

**Comment by patthiel** [comment]
So far, I've tried getting KDX Client working in the same docker container environment, but with X11 dev libraries installed w/xquartz (X11) and setting the DISPLAY env variable. I'll post instructions when i have some time and something close to working

**Comment by patthiel** [comment]
following up: i've had success running kdx client via [docker-wine](https://github.com/scottyhardy/docker-wine). I ran into some roadblocks running it in a vanilla ubuntu container connected to xquartz.
