### ISSUE TITLE
KDX client for Unix/Darwin?

### ISSUE THREAD

**Issue by barracuda156** [patthiel/docker-kdx-server#3]
Is it possible to build it for Darwin?

**Comment by patthiel** [comment]
thanks for the issue @barracuda156.  Natively, 

I attempted this in https://github.com/patthiel/docker-kdx-server/issues/1#issuecomment-933543313 by running Linux version of the KDX Client in a docker container with the DISPLAY hooked up to a X11 window manager. I didn't manage to get it working there, but I did manage to get it working via [docker-wine](https://hub.docker.com/r/scottyhardy/docker-wine/) using the windows binary. 

You can also run the windows binary on your mac through wine directly without the use of docker. 

You should be able to find the windows binary here: https://preterhuman.net/gethotlinekdx.php

hope this helps

**Comment by barracuda156** [comment]
> thanks for the issue @barracuda156.
> You should be able to find the windows binary here: https://preterhuman.net/gethotlinekdx.php
> hope this helps

Thank you!
Yes, until Catalina (I think) Wine worked, and on later systems Windows versions of KDX can run via CrossOver.
I just hoped there could be a better solution.

**Comment by patthiel** [comment]
Closing this, if anyone wants to submit a guide to doing this they are more than welcome to open up a pull request with it. Thanks!

**Comment by barracuda156** [comment]
@patthiel Thank you. I have it in mind, but been busy with other stuff recently. Will update, if anything gonna be there.
